apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: aofekiko
spec:
  profile:
    displayName: Ofek Aizik
    email: aofekiko@gmail.com
    picture: https://avatars.githubusercontent.com/u/20258376?v=4
  memberOf: [rnd]
